### ISSUE TITLE
description of function get_threshold_by_fq?

### ISSUE THREAD

**Issue by whaleloops** [discnet2022/discnet#1]
Q1. What is the use of [get_threshold_by_fq](https://github.com/discnet2022/discnet/blob/master/utils/evaluation.py#L18)?
How do you determine split_point=10, head_t=0.3, tail_t=0.08 [here](https://github.com/discnet2022/discnet/blob/master/train_discnet.py#L244)?
Sorry if I missed these details in the paper.

Q2: How did you implement gate vectors equation 6, could you point me to the related code section?

Q3: Would **3.2.2 Reconciling the class-imbalance** still works if not get_threshold_by_fq, instead, using [find_threshold_micro](https://github.com/GanjinZero/ICD-MSMN/blob/master/find_threshold.py#L4)?

**Comment by discnet2022** [comment]
Sorry for the late response:
Q1 and Q3: Yes, we lowered the threshold to improve the recall for rare codes based on an analysis of the precision-recall curve on the development dataset. However, the effectiveness of the reconciliation mechanism can also be demonstrated by other metrics that are not related to the threshold, such as the AUC and precision at k.
Q2: Yes, discnet/models_discnet_re/network.py line 173-188
