### ISSUE TITLE
"target_codes" Issue in preprocessing.ipynb

### ISSUE THREAD

**Issue by atharva-naik** [discnet2022/discnet#2]
Hi! Our team is trying to reproduce this work for a research project. However we are unable to run the preprocessing jupyter notebook present in this repo.

The ```data_dic``` list of dictionaries only has the following 3 keys: "text", "labels" & "data". The code expects a key "target_codes" to be present as well. How to fix this issue?
![image](https://user-images.githubusercontent.com/45898380/201231600-dbf5d0cc-05c1-40b1-9a50-866bc5d6e1d4.png)

**Comment by freshjarman** [comment]
> Hi! Our team is trying to reproduce this work for a research project. However we are unable to run the preprocessing jupyter notebook present in this repo.
> 
> The `data_dic` list of dictionaries only has the following 3 keys: "text", "labels" & "data". The code expects a key "target_codes" to be present as well. How to fix this issue? ![image](https://user-images.githubusercontent.com/45898380/201231600-dbf5d0cc-05c1-40b1-9a50-866bc5d6e1d4.png)

-----------------------------------------------------------------------------------------------------------------------------------------

Hi, have u fixed this issue? I am facing the same issue.  I think maybe u can change like:

```python
if len(data_dic[k]['labels']) != 0: 
    train_set[k] = data_dic[k]   # here, 'data' should be changed into 'data_dic', right?
```

> Hope to receive your reply soon.

**Comment by discnet2022** [comment]
Sorry for the late response. The bug has been fixed. You can also contact me to get the preprocessed dataset (please refer to the readme for more information).
