### ISSUE TITLE
KeyError: 'char_len'

### ISSUE THREAD

**Issue by mingyangligithub** [discnet2022/discnet#3]
A problem when running train_discnet.py
all_hadm_ids = sorted(all_hadm_ids, key=lambda x: int(self.data[x]['char_len']))
Each piece of data has 'labels', 'text', 'data', doesn't have 'char_len'.

**Comment by discnet2022** [comment]
Sorry for the late response. The bug has been fixed. You can also contact me to get the preprocessed dataset (please refer to the readme for more information).
